// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cksgusvgccxrzpxbcdzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrc2d1c3ZnY2N4cnpweGJjZHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDQzMDcsImV4cCI6MjA2OTkyMDMwN30.E9Ip71YaM9gtl_Kk-05dui0Vc_fWhZRpKQgKEalzs-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});